<!--指定存在的镜像-->
FROM java:8
<!--指向的一个临时文件，用于存储tomcat工作-->
VOLUME /tmp/tomcat
<!--复制文件并且重命名文件-->
ADD spring-boot-docker-0.0.1-SNAPSHOT.jar springboot-docker.jar
<!--初始化配置或者自定义配置-->
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/springboot-docker.jar"]